name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write
    steps:
      - name: Fetch Git repository and checkout
        uses: "actions/checkout@v4"

      - uses: ./.github/actions/setup
      - uses: ./.github/actions/lint
      - uses: ./.github/actions/release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
